services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fabrica
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fabrica
      DB_USER: postgres
      DB_PASS: postgres
      PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
